### ISSUE TITLE
Logger error 

### ISSUE THREAD

**Issue by danyaljj** [iamaaditya/neural-paraphrase-generation#11]
Getting this error: 
```
(env3.5) khashab2@austen:/shared/shelley/khashab2/neural-paraphrase-generation$ python3.5 train.py 
Traceback (most recent call last):
  File "train.py", line 47, in <module>
    tf.app.run()
  File "/shared/shelley/khashab2/neural-paraphrase-generation/env3.5/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "train.py", line 34, in main
    tf.logging._logger.setLevel(logging.INFO)
AttributeError: module 'tensorflow._api.v1.logging' has no attribute '_logger'
```

Suspect that it has to do with old tensorflow version. I am using `tensorflow-1.12.0` (and tried it on Python2, 3, 3.5).

**Comment by joseph12346** [comment]
try use
tf.logging.set_verbosity(logging.INFO)

**Comment by iamaaditya** [comment]
Fixed.
